server:
  port: 8081
spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:db:DB_CLOSE_DELAY=-;TRACE_LEVEL_FILE=4"
    username: sa
    password: sa
    initialization-mode: always
  h2:
    console:
      enabled: true

logging:
  pattern:
    console: "%d{HH::mm.ss.SSS} {%thread} %-5level %logger{36} : %msg%n"

  level:
    org.springframework.jdbc.datasource: debug
    com.example: debug